services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATA_DIR=/app/data
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    networks:
      - luminet-network

networks:
  luminet-network:
    driver: bridge