services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATA_DIR=/app/data
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data  # Mount local data directory for development
    networks:
      - luminet-network

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - luminet-network

networks:
  luminet-network:
    driver: bridge